{{- if .Values.etlUtils.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "etlUtils.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etlUtils.commonLabels" . | nindent 4 }}
  {{- with .Values.global.podAnnotations}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "etlUtils.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "etlUtils.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ template "etlUtils.name" . }}
    spec:
      restartPolicy: Always
      volumes:
        {{- if .Values.etlUtils.thanosSourceBucketSecret }}
        - name: etl-bucket-config
          secret:
            defaultMode: 420
            secretName: {{ .Values.etlUtils.thanosSourceBucketSecret }}
        {{- end }}
        {{- if .Values.kubecostModel.federatedStorageConfigSecret }}
        - name: federated-storage-config
          secret:
            defaultMode: 420
            secretName: {{ .Values.kubecostModel.federatedStorageConfigSecret }}
        {{- end }}
        {{/*
        Could rename this, I don't think it needs to persist
        */}}
        - name: persistent-configs
          emptyDir: {}
      serviceAccountName: {{ template "cost-analyzer.serviceAccountName" . }}
      containers:
        - name: {{ template "etlUtils.name" . }}
          {{- if .Values.kubecostModel }}
          {{- if .Values.kubecostModel.openSourceOnly }}
          {{- fail "ETL Utils cannot be used with open source only" }}
          {{- else if .Values.etlUtils.fullImageName }}
          image: {{ .Values.etlUtils.fullImageName }}
          {{- else if .Values.kubecostModel.fullImageName }}
          image: {{ .Values.kubecostModel.fullImageName }}
          {{- else if .Values.imageVersion }}
          image: {{ .Values.kubecostModel.image }}:{{ .Values.imageVersion }}
          {{- else if eq "development" .Chart.AppVersion }}
          image: gcr.io/kubecost1/cost-model-nightly:latest
          {{- else }}
          image: {{ .Values.kubecostModel.image }}:prod-{{ $.Chart.AppVersion }}
          {{ end }}
          {{- else }}
          image: gcr.io/kubecost1/cost-model:prod-{{ $.Chart.AppVersion }}
          {{ end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9006
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 200
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9006
            initialDelaySeconds: 10
            periodSeconds: 5
          imagePullPolicy: Always
          args: ["etl-utils"]
          ports:
            - name: api
              containerPort: 9006
              protocol: TCP
          resources:
            {{- toYaml .Values.etlUtils.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.etlUtils.thanosSourceBucketSecret }}
            - name: etl-bucket-config
              mountPath: /var/configs/etl
              readOnly: true
          {{- end }}
          env:
            - name: CONFIG_PATH
              value: /var/configs/
            {{- if .Values.etlUtils.thanosSourceBucketSecret }}
            - name: ETL_BUCKET_CONFIG
            {{- if (.Values.kubecostModel).etlBucketConfigSecretFileName }}
              value: "/var/configs/etl/{{ .Values.kubecostModel.etlBucketConfigSecretFileName }}"
            {{- else }}
              value: "/var/configs/etl/object-store.yaml"
            {{- end }}
            {{- end}}
            {{- range $key, $value := .Values.etlUtils.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
{{- if .Values.etlUtils.thanosConverter.enabled }}
        - name: thanos-converter
          image: gcr.io/kubecost1/cost-model-nightly:latest
          imagePullPolicy: Always
          args: ["cost-model"]
          resources:
            {{- toYaml .Values.etlUtils.resources | nindent 12 }}
          volumeMounts:
            - name: persistent-configs
              mountPath: /var/configs
            - name: etl-bucket-config
              mountPath: /var/configs/etl
              readOnly: true
          env:
            - name: CONFIG_PATH
              value: /var/configs/
            {{- if .Values.etlUtils.thanosSourceBucketSecret }}
            - name: ETL_BUCKET_CONFIG
            {{- if (.Values.kubecostModel).etlBucketConfigSecretFileName }}
              value: /var/configs/etl/{{ .Values.kubecostModel.etlBucketConfigSecretFileName }}
            {{- else }}
              value: "/var/configs/etl/object-store.yaml"
            {{- end }}
            {{- end }}
            - name: MAX_QUERY_CONCURRENCY
              value: {{ (quote .Values.kubecostModel.maxQueryConcurrency) | default (quote 10) }}
            - name: THANOS_ENABLED
              value: "true"
            - name: THANOS_QUERY_URL
              value: http://thanos-query-frontend.thanos:9090
            - name: THANOS_QUERY_OFFSET
              value: {{ (.Values.global.thanos).queryOffset | default "3h" }}
            - name: THANOS_MAX_SOURCE_RESOLUTION
              value: {{ (.Values.kubecostModel).maxSourceResolution | default "raw" }}
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: http://thanos-query-frontend.thanos:9090
            - name: CLOUD_PROVIDER_API_KEY
              value: "AIzaSyDXQPG_MHUEy9neR7stolq6l0ujXmjJlvk"
            - name: CLUSTER_ID
              value: {{ .Values.prometheus.server.global.external_labels.cluster_id }}
          {{- if .Values.etlUtils.thanosConverter.env }}
          {{- range $key, $value := .Values.etlUtils.thanosConverter.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
{{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
      {{- with .Values.etlUtils.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.etlUtils.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.etlUtils.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
